using BlazorMauiShared.Models.Assessment;
using BlazorMauiShared.Models.Asset;
using BlazorMauiShared.Models.CompensatingControl;
using BlazorMauiShared.Models.ComplianceOfficer;
using BlazorMauiShared.Models.Control;
using BlazorMauiShared.Models.CryptographicInventory;
using BlazorMauiShared.Models.Evidence;
using BlazorMauiShared.Models.Merchant;
using BlazorMauiShared.Models.NetworkSegmentation;
using BlazorMauiShared.Models.PaymentChannel;
using BlazorMauiShared.Models.ServiceProvider;

using PCIShield.BlazorMauiShared.Models;
using PCIShield.BlazorMauiShared.Models.Merchant;
using PCIShield.Domain.ModelsDto;

namespace PCIShield.Client.Services.Merchant;

public interface IHttpMerchantClientService
{
    Task<UpdateMerchantResponse> UpdatePutMerchantAsync(UpdateMerchantRequest data);
    Task<CreateMerchantResponse> CreatePostMerchantAsync(CreateMerchantRequest data);
    Task<GetByIdMerchantResponse> GetLastCreatedMerchantAsync();
    Task<DeleteMerchantResponse> DeleteMerchantAsync(Guid merchantId);
    Task<ListMerchantResponse?> GetFilteredMerchantListAsync(int pageNumber, int pageSize, Dictionary<string, string> filters = null, List<PCIShieldLib.SharedKernel.Interfaces.Sort> sorting = null);
    Task<ListMerchantResponse?> GetPagedMerchantsListAsync(int pageNumber, int pageSize);
    Task<List<MerchantDto>> SearchMerchantByMerchantAsync(string searchTerm);
    Task<GetByIdMerchantResponse> GetOneFullMerchantByIdAsync(Guid merchantId, bool withPostGraph = false);
    Task<SpecificationPerformanceResponse<MerchantDto>> RunMerchantPerformanceTests(Guid merchantId);
    Task<CreateAssessmentResponse> CreateAssessmentAsync(AssessmentDto data);
    Task<AssessmentDto> UpdateAssessmentAsync(AssessmentDto data);
    Task DeleteAssessmentAsync(Guid assessmentId);
    Task<GetByIdAssessmentResponse> GetOneFullAssessmentByIdAsync(Guid assessmentId);
    Task<ListAssessmentResponse?> GetFilteredAssessmentsListAsync(int pageNumber, int pageSize, Dictionary<string, string> filters = null, List< PCIShieldLib.SharedKernel.Interfaces.Sort> sorting = null);
    Task<ListAssessmentResponse?> GetPagedAssessmentsListAsync(int pageNumber, int pageSize);
    Task<List<AssessmentDto>> SearchAssessmentsAsync(string searchTerm);
    Task<CreateAssetResponse> CreateAssetAsync(AssetDto data);
    Task<AssetDto> UpdateAssetAsync(AssetDto data);
    Task DeleteAssetAsync(Guid assetId);
    Task<GetByIdAssetResponse> GetOneFullAssetByIdAsync(Guid assetId);
    Task<ListAssetResponse?> GetFilteredAssetsListAsync(int pageNumber, int pageSize, Dictionary<string, string> filters = null, List< PCIShieldLib.SharedKernel.Interfaces.Sort> sorting = null);
    Task<ListAssetResponse?> GetPagedAssetsListAsync(int pageNumber, int pageSize);
    Task<List<AssetDto>> SearchAssetsAsync(string searchTerm);
    Task<CreateCompensatingControlResponse> CreateCompensatingControlAsync(CompensatingControlDto data);
    Task<CompensatingControlDto> UpdateCompensatingControlAsync(CompensatingControlDto data);
    Task DeleteCompensatingControlAsync(Guid compensatingControlId);
    Task<GetByIdCompensatingControlResponse> GetOneFullCompensatingControlByIdAsync(Guid compensatingControlId);
    Task<ListCompensatingControlResponse?> GetFilteredCompensatingControlsListAsync(int pageNumber, int pageSize, Dictionary<string, string> filters = null, List< PCIShieldLib.SharedKernel.Interfaces.Sort> sorting = null);
    Task<ListCompensatingControlResponse?> GetPagedCompensatingControlsListAsync(int pageNumber, int pageSize);
    Task<List<CompensatingControlDto>> SearchCompensatingControlsAsync(string searchTerm);
    Task<CreateComplianceOfficerResponse> CreateComplianceOfficerAsync(ComplianceOfficerDto data);
    Task<ComplianceOfficerDto> UpdateComplianceOfficerAsync(ComplianceOfficerDto data);
    Task DeleteComplianceOfficerAsync(Guid complianceOfficerId);
    Task<GetByIdComplianceOfficerResponse> GetOneFullComplianceOfficerByIdAsync(Guid complianceOfficerId);
    Task<ListComplianceOfficerResponse?> GetFilteredComplianceOfficersListAsync(int pageNumber, int pageSize, Dictionary<string, string> filters = null, List< PCIShieldLib.SharedKernel.Interfaces.Sort> sorting = null);
    Task<ListComplianceOfficerResponse?> GetPagedComplianceOfficersListAsync(int pageNumber, int pageSize);
    Task<List<ComplianceOfficerDto>> SearchComplianceOfficersAsync(string searchTerm);
    Task<CreateCryptographicInventoryResponse> CreateCryptographicInventoryAsync(CryptographicInventoryDto data);
    Task<CryptographicInventoryDto> UpdateCryptographicInventoryAsync(CryptographicInventoryDto data);
    Task DeleteCryptographicInventoryAsync(Guid cryptographicInventoryId);
    Task<GetByIdCryptographicInventoryResponse> GetOneFullCryptographicInventoryByIdAsync(Guid cryptographicInventoryId);
    Task<ListCryptographicInventoryResponse?> GetFilteredCryptographicInventoriesListAsync(int pageNumber, int pageSize, Dictionary<string, string> filters = null, List< PCIShieldLib.SharedKernel.Interfaces.Sort> sorting = null);
    Task<ListCryptographicInventoryResponse?> GetPagedCryptographicInventoriesListAsync(int pageNumber, int pageSize);
    Task<List<CryptographicInventoryDto>> SearchCryptographicInventoriesAsync(string searchTerm);
    Task<CreateEvidenceResponse> CreateEvidenceAsync(EvidenceDto data);
    Task<EvidenceDto> UpdateEvidenceAsync(EvidenceDto data);
    Task DeleteEvidenceAsync(Guid evidenceId);
    Task<GetByIdEvidenceResponse> GetOneFullEvidenceByIdAsync(Guid evidenceId);
    Task<ListEvidenceResponse?> GetFilteredEvidencesListAsync(int pageNumber, int pageSize, Dictionary<string, string> filters = null, List< PCIShieldLib.SharedKernel.Interfaces.Sort> sorting = null);
    Task<ListEvidenceResponse?> GetPagedEvidencesListAsync(int pageNumber, int pageSize);
    Task<List<EvidenceDto>> SearchEvidencesAsync(string searchTerm);
    Task<CreateNetworkSegmentationResponse> CreateNetworkSegmentationAsync(NetworkSegmentationDto data);
    Task<NetworkSegmentationDto> UpdateNetworkSegmentationAsync(NetworkSegmentationDto data);
    Task DeleteNetworkSegmentationAsync(Guid networkSegmentationId);
    Task<GetByIdNetworkSegmentationResponse> GetOneFullNetworkSegmentationByIdAsync(Guid networkSegmentationId);
    Task<ListNetworkSegmentationResponse?> GetFilteredNetworkSegmentationsListAsync(int pageNumber, int pageSize, Dictionary<string, string> filters = null, List< PCIShieldLib.SharedKernel.Interfaces.Sort> sorting = null);
    Task<ListNetworkSegmentationResponse?> GetPagedNetworkSegmentationsListAsync(int pageNumber, int pageSize);
    Task<List<NetworkSegmentationDto>> SearchNetworkSegmentationsAsync(string searchTerm);
    Task<CreatePaymentChannelResponse> CreatePaymentChannelAsync(PaymentChannelDto data);
    Task<PaymentChannelDto> UpdatePaymentChannelAsync(PaymentChannelDto data);
    Task DeletePaymentChannelAsync(Guid paymentChannelId);
    Task<GetByIdPaymentChannelResponse> GetOneFullPaymentChannelByIdAsync(Guid paymentChannelId);
    Task<ListPaymentChannelResponse?> GetFilteredPaymentChannelsListAsync(int pageNumber, int pageSize, Dictionary<string, string> filters = null, List< PCIShieldLib.SharedKernel.Interfaces.Sort> sorting = null);
    Task<ListPaymentChannelResponse?> GetPagedPaymentChannelsListAsync(int pageNumber, int pageSize);
    Task<List<PaymentChannelDto>> SearchPaymentChannelsAsync(string searchTerm);
    Task<CreateServiceProviderResponse> CreateServiceProviderAsync(ServiceProviderDto data);
    Task<ServiceProviderDto> UpdateServiceProviderAsync(ServiceProviderDto data);
    Task DeleteServiceProviderAsync(Guid serviceProviderId);
    Task<GetByIdServiceProviderResponse> GetOneFullServiceProviderByIdAsync(Guid serviceProviderId);
    Task<ListServiceProviderResponse?> GetFilteredServiceProvidersListAsync(int pageNumber, int pageSize, Dictionary<string, string> filters = null, List< PCIShieldLib.SharedKernel.Interfaces.Sort> sorting = null);
    Task<ListServiceProviderResponse?> GetPagedServiceProvidersListAsync(int pageNumber, int pageSize);
    Task<List<ServiceProviderDto>> SearchServiceProvidersAsync(string searchTerm);
    Task<ListControlResponse?> GetFilteredControlsListAsync(int pageNumber, int pageSize, Dictionary<string, string> filters = null, List< PCIShieldLib.SharedKernel.Interfaces.Sort> sorting = null);
    Task<ListControlResponse?> GetPagedControlsListAsync(int pageNumber, int pageSize);
    Task<List<ControlDto>> SearchControlsAsync(string searchTerm);
    void Dispose();
}