using System.Net;
using System.Net.Sockets;
using System.Runtime.InteropServices.JavaScript;
using System.Security;
using System.Security.Authentication;
using System.Text.Json;
using Microsoft.AspNetCore.SignalR;
namespace PCIShield.Client.Services.Common
{
    public static class ErrorHandlingService
    {
        public static string GetUserFriendlyErrorMessage(Exception ex)
        {
            if (ex is HttpRequestException httpEx)
            {
                return httpEx.StatusCode switch
                {
                    HttpStatusCode.Unauthorized => "Your session has expired. Please log in again.",
                    HttpStatusCode.Forbidden => "You don't have permission to perform this action. Please contact your administrator.",
                    HttpStatusCode.NotFound => "The requested information could not be found. It may have been deleted or moved.",
                    HttpStatusCode.BadRequest => "There was a problem with the request. Please check your input and try again.",
                    HttpStatusCode.Conflict => "This record is being edited by another user. Please try again later.",
                    HttpStatusCode.PreconditionFailed => "The data has changed since you loaded it. Please refresh and try again.",
                    HttpStatusCode.RequestTimeout => "The request took too long to complete. Please check your internet connection.",
                    HttpStatusCode.TooManyRequests => "Too many requests. Please wait a moment before trying again.",
                    HttpStatusCode.UnprocessableEntity => "The provided data cannot be processed. Please check your input.",
                    HttpStatusCode.InternalServerError => "An unexpected server error occurred. Please try again later.",
                    HttpStatusCode.BadGateway => "The service is temporarily unavailable. Please try again in a few minutes.",
                    HttpStatusCode.ServiceUnavailable => "The system is undergoing maintenance. Please try again later.",
                    HttpStatusCode.GatewayTimeout => "The server took too long to respond. Please try again.",
                    _ => "There was a problem connecting to the server. Please try again."
                };
            }
            return ex switch
            {
                TaskCanceledException => "The request was cancelled. Please check your internet connection and try again.",
                TimeoutException => "The request timed out. Please check your internet connection and try again.",
                SocketException => "Unable to connect to the server. Please check your network connection.",
                JsonException => "There was a problem processing the server response. Please try refreshing the page.",
                InvalidDataException => "The data format is incorrect. Please check your input.",
                ArgumentException argEx => $"Invalid input provided: {argEx.Message}",
                FluentValidation.ValidationException fluentEx => string.Join(" ", fluentEx.Errors.Select(e => e.ErrorMessage)),
                AuthenticationException => "Your session has expired. Please log in again.",
                SecurityException => "You don't have the required security permissions.",
                JSException => "There was a problem executing browser functionality. Please refresh the page.",
                FileNotFoundException => "The requested file could not be found.",
                IOException => "There was a problem accessing the file. Please try again.",
                HubException => "Lost connection to real-time updates. Please refresh the page.",
                InvalidOperationException => "The operation could not be completed. Please try again.",
                AggregateException aggEx => GetMostRelevantMessage(aggEx),
                _ => "An unexpected error occurred. Please try refreshing the page."
            };
        }
        public static string GetContextualErrorMessage(Exception ex, ClientOperationContext context)
        {
            var baseMessage = GetUserFriendlyErrorMessage(ex);
            return context switch
            {
                ClientOperationContext.Loading => "Unable to load data. Please refresh the page.",
                ClientOperationContext.Saving => "Unable to save changes. Please try again.",
                ClientOperationContext.Uploading => "Unable to upload file. Please check your connection.",
                ClientOperationContext.Downloading => "Unable to download file. Please try again.",
                ClientOperationContext.Authentication => "Authentication failed. Please log in again.",
                ClientOperationContext.FormSubmission => "Unable to submit form. Please check your input.",
                ClientOperationContext.Delete => "Unable to delete item. Please try again.",
                ClientOperationContext.Update => "Unable to update. Please try again.",
                ClientOperationContext.Create => "Unable to create new item. Please try again.",
                ClientOperationContext.CustomerInitialization => "Unable to initialize customer data. Please refresh the page.",
                ClientOperationContext.CustomerEdit => "Unable to save customer changes. Please verify your input and try again.",
                ClientOperationContext.CustomerDelete => "Unable to delete customer. Please try again.",
                ClientOperationContext.CustomerSearch => "Unable to search customers. Please try again.",
                ClientOperationContext.CustomerExport => "Unable to export customer data. Please try again.",
                ClientOperationContext.CustomerImport => "Unable to import customer data. Please check the file format.",
                ClientOperationContext.StatusChange => "Unable to change customer status. Please ensure all required fields are completed.",
                ClientOperationContext.WorkflowOperation => "Unable to process workflow operation. Please ensure all conditions are met.",
                ClientOperationContext.ApprovalOperation => "Unable to process approval operation. Please try again.",
                ClientOperationContext.WorkflowValidation => "Unable to validate workflow. Please check all requirements.",
                ClientOperationContext.StateTransition => "Unable to transition state. Please check conditions.",
                ClientOperationContext.AddressOperation => "Unable to process address operation. Please try again.",
                ClientOperationContext.AddressValidation => "Unable to validate address. Please check the input.",
                ClientOperationContext.AddressCreate => "Unable to create new address. Please try again.",
                ClientOperationContext.AddressUpdate => "Unable to update address. Please try again.",
                ClientOperationContext.AddressDelete => "Unable to delete address. Please try again.",
                ClientOperationContext.ContactOperation => "Unable to process contact operation. Please try again.",
                ClientOperationContext.ContactValidation => "Unable to validate contact. Please check the input.",
                ClientOperationContext.ContactCreate => "Unable to create new contact. Please try again.",
                ClientOperationContext.ContactUpdate => "Unable to update contact. Please try again.",
                ClientOperationContext.ContactDelete => "Unable to delete contact. Please try again.",
                ClientOperationContext.DocumentOperation => "Unable to process document operation. Please try again.",
                ClientOperationContext.DocumentValidation => "Unable to validate document. Please check the input.",
                ClientOperationContext.DocumentCreate => "Unable to create new document. Please try again.",
                ClientOperationContext.DocumentUpdate => "Unable to update document. Please try again.",
                ClientOperationContext.DocumentDelete => "Unable to delete document. Please try again.",
                ClientOperationContext.PaymentOperation => "Unable to process payment operation. Please try again.",
                ClientOperationContext.PaymentValidation => "Unable to validate payment. Please check the input.",
                ClientOperationContext.PaymentCreate => "Unable to create new payment. Please try again.",
                ClientOperationContext.PaymentUpdate => "Unable to update payment. Please try again.",
                ClientOperationContext.PaymentDelete => "Unable to delete payment. Please try again.",
                ClientOperationContext.InvoiceOperation => "Unable to process invoice operation. Please try again.",
                ClientOperationContext.InvoiceValidation => "Unable to validate invoice. Please check the input.",
                ClientOperationContext.InvoiceCreate => "Unable to create new invoice. Please try again.",
                ClientOperationContext.InvoiceUpdate => "Unable to update invoice. Please try again.",
                ClientOperationContext.InvoiceDelete => "Unable to delete invoice. Please try again.",
                ClientOperationContext.EmailOperation => "Unable to process email address operation. Please try again.",
                ClientOperationContext.EmailValidation => "Unable to validate email. Please check the format.",
                ClientOperationContext.EmailCreate => "Unable to add email address. Please try again.",
                ClientOperationContext.EmailUpdate => "Unable to update email address. Please try again.",
                ClientOperationContext.EmailDelete => "Unable to delete email address. Please try again.",
                ClientOperationContext.PhoneOperation => "Unable to process phone number operation. Please try again.",
                ClientOperationContext.PhoneValidation => "Unable to validate phone number. Please check the format.",
                ClientOperationContext.PhoneCreate => "Unable to add phone number. Please try again.",
                ClientOperationContext.PhoneUpdate => "Unable to update phone number. Please try again.",
                ClientOperationContext.PhoneDelete => "Unable to delete phone number. Please try again.",
                ClientOperationContext.SalespersonOperation => "Unable to process salesperson operation. Please try again.",
                ClientOperationContext.SalespersonValidation => "Unable to validate salesperson. Please check the input.",
                ClientOperationContext.SalespersonCreate => "Unable to add salesperson. Please try again.",
                ClientOperationContext.SalespersonUpdate => "Unable to update salesperson. Please try again.",
                ClientOperationContext.SalespersonDelete => "Unable to delete salesperson. Please try again.",
                ClientOperationContext.TaxOperation => "Unable to process tax system operation. Please try again.",
                ClientOperationContext.TaxValidation => "Unable to validate tax information. Please check the input.",
                ClientOperationContext.TaxCreate => "Unable to add tax information. Please try again.",
                ClientOperationContext.TaxUpdate => "Unable to update tax information. Please try again.",
                ClientOperationContext.TaxDelete => "Unable to delete tax information. Please try again.",
                ClientOperationContext.HubConnection => "Unable to establish real-time connection. Some features may be limited.",
                ClientOperationContext.HubReconnection => "Attempting to restore real-time connection...",
                ClientOperationContext.HubDisconnection => "Lost connection to server. Please check your internet connection.",
                ClientOperationContext.SignalREvent => "Unable to process real-time update. Please refresh the page.",
                ClientOperationContext.DataFormatting => "Unable to format data. Please check your input format.",
                ClientOperationContext.DataValidation => "Unable to validate data. Please check your input.",
                ClientOperationContext.DataSynchronization => "Unable to synchronize data. Please try again.",
                ClientOperationContext.TabOperation => "Unable to load tab content. Please try again.",
                ClientOperationContext.TabActivation => "Unable to activate tab. Please try again.",
                ClientOperationContext.TabDataLoad => "Unable to load tab data. Please refresh.",
                ClientOperationContext.FormValidation => "Form validation failed. Please check your input.",
                ClientOperationContext.StateTracking => "Unable to track changes. Please refresh the page.",
                ClientOperationContext.DirtyStateChange => "Unable to save changes. Please try again.",
                ClientOperationContext.MemoryAllocation => "Unable to allocate memory. Please refresh the page.",
                ClientOperationContext.MemoryCleanup => "Unable to clean up resources. Please refresh the page.",
                ClientOperationContext.BufferOperation => "Unable to process data buffer. Please try again.",
                ClientOperationContext.ExportOperation => "Unable to export data. Please try again.",
                ClientOperationContext.ImportOperation => "Unable to import data. Please check the file format.",
                ClientOperationContext.PrintOperation => "Unable to print. Please try again.",
                ClientOperationContext.LocalStorageOperation => "Unable to access local storage. Please check browser settings.",
                _ => baseMessage
            };
        }
        public static bool TryParseContext(string contextName, out ClientOperationContext context)
        {
            return Enum.TryParse(contextName, out context);
        }
        private static string GetMostRelevantMessage(AggregateException aggEx)
        {
            if (aggEx.InnerExceptions.Count == 0)
                return "Multiple errors occurred. Please try again.";
            var mostSpecific = aggEx.InnerExceptions
                .FirstOrDefault(e => e is not Exception)
                ?? aggEx.InnerExceptions.First();
            return GetUserFriendlyErrorMessage(mostSpecific);
        }
        public enum ClientOperationContext
        {
            Loading,
            Saving,
            Uploading,
            Downloading,
            Authentication,
            FormSubmission,
            Delete,
            Update,
            Create,
            CustomerInitialization,
            CustomerEdit,
            CustomerDelete,
            CustomerSearch,
            CustomerExport,
            CustomerImport,
            StatusChange,
            WorkflowOperation,
            ApprovalOperation,
            WorkflowValidation,
            StateTransition,
            AddressOperation,
            AddressValidation,
            AddressCreate,
            AddressUpdate,
            AddressDelete,
            ContactOperation,
            ContactValidation,
            ContactCreate,
            ContactUpdate,
            ContactDelete,
            DocumentOperation,
            DocumentValidation,
            DocumentCreate,
            DocumentUpdate,
            DocumentDelete,
            PaymentOperation,
            PaymentValidation,
            PaymentCreate,
            PaymentUpdate,
            PaymentDelete,
            InvoiceOperation,
            InvoiceValidation,
            InvoiceCreate,
            InvoiceUpdate,
            InvoiceDelete,
            EmailOperation,
            EmailValidation,
            EmailCreate,
            EmailUpdate,
            EmailDelete,
            PhoneOperation,
            PhoneValidation,
            PhoneCreate,
            PhoneUpdate,
            PhoneDelete,
            SalespersonOperation,
            SalespersonValidation,
            SalespersonCreate,
            SalespersonUpdate,
            SalespersonDelete,
            TaxOperation,
            TaxValidation,
            TaxCreate,
            TaxUpdate,
            TaxDelete,
            HubConnection,
            HubReconnection,
            HubDisconnection,
            SignalREvent,
            DataFormatting,
            DataValidation,
            DataSynchronization,
            TabOperation,
            TabActivation,
            TabDataLoad,
            FormValidation,
            StateTracking,
            DirtyStateChange,
            MemoryAllocation,
            MemoryCleanup,
            BufferOperation,
            ExportOperation,
            ImportOperation,
            PrintOperation,
            LocalStorageOperation,
            DocumentIdentificationCreate,
            DocumentIdentificationDelete,
            EconomicActivitySystemTypeCreate,
            EconomicActivitySystemTypeDelete,
            EmailAddressCreate,
            EmailAddressDelete,
            PhoneNumberCreate,
            PhoneNumberDelete,
            TaxSystemTypeCreate,
            TaxSystemTypeDelete,
            CustomerPaymentCreate,
            CustomerPaymentUpdate,
            CustomerPaymentDelete,
            InvoiceAccountReceivableCreate,
            InvoiceAccountReceivableUpdate,
            InvoiceAccountReceivableDelete,
            InvoiceDetailCreate,
            InvoiceDetailUpdate,
            InvoiceDetailDelete,
            InvoiceDetailGroupCreate,
            InvoiceDetailGroupUpdate,
            InvoiceDetailGroupDelete,
            CustomerCreate,
            BankTransactionCreate,
            BankTransactionUpdate,
            BankTransactionDelete,
            PurchaseDetailCreate,
            PurchaseDetailUpdate,
            PurchaseDetailDelete,
            PriceUserTypeCreate,
            PriceUserTypeDelete,
            MeasurementUnitSystemTypeDelete,
            MeasurementUnitSystemTypeCreate,
            CategoryDelete,
            CategoryCreate,
            BankAccountCreate,
            BankAccountUpdate,
            BankAccountDelete,
            ElectronicDocumentCreate,
            ElectronicDocumentDelete,
            PurchaseAccountPayableCreate,
            PurchaseAccountPayableUpdate,
            PurchaseAccountPayableDelete,
            SupplierPaymentCreate,
            SupplierPaymentUpdate,
            PurchaseCreate,
            SupplierPaymentDelete,
            SupplierInitialization,
            PurchaseUpdate,
            PurchaseDelete,
            CustomerPaymentInitialization,
            FieldUpdate,
            EconomicActivitySystemTypeUpdate,
            EmailAddressUpdate,
            PhoneNumberUpdate,
            AssessmentCreate,
            AssessmentUpdate,
            AssessmentDelete,
            AssetCreate,
            AssetUpdate,
            AssetDelete,
            CompensatingControlCreate,
            CompensatingControlDelete,
            CompensatingControlUpdate,
            ComplianceOfficerCreate,
            ComplianceOfficerUpdate,
            ComplianceOfficerDelete,
            CryptographicInventoryCreate,
            CryptographicInventoryUpdate,
            CryptographicInventoryDelete,
            EvidenceCreate,
            EvidenceUpdate,
            EvidenceDelete,
            NetworkSegmentationCreate,
            NetworkSegmentationUpdate,
            NetworkSegmentationDelete,
            PaymentChannelCreate,
            PaymentChannelUpdate,
            PaymentChannelDelete,
            ServiceProviderCreate,
            ServiceProviderUpdate,
            ServiceProviderDelete,
            ROCPackageUpdate,
            ROCPackageCreate,
            ROCPackageDelete,
            ControlCreate,
            ControlDelete
        }
    }
}
